uses sshfs to mount remote filesystems

diff --git a/scripts/common/create_cloud_snapshot b/scripts/common/create_cloud_snapshot
--- a/scripts/common/create_cloud_snapshot
+++ b/scripts/common/create_cloud_snapshot
@@ -19,6 +19,21 @@ ssh $opts $user@$namescheme "sudo cp -f /home/$user/slurm.cert /etc/slurm/slurm.
 # Copy back ssh key
 ssh $opts $user@$namescheme "cat ~/.ssh/id_rsa.pub" >> ~/.ssh/authorized_keys
 
+# Set up sshfs
+sudo ln -s /home/`whoami` /home/$user
+uid="`ls -n /home/ | grep " `whoami`$" | awk '{print $3}'`"
+gid="`ls -n /home/ | grep " `whoami`$" | awk '{print $4}'`"
+ssh $opts $user@$namescheme "echo $user:$uid | sudo tee /root/sshfs_uids && echo $user:$gid | sudo tee /root/sshfs_gids"
+
+# Test sshfs
+clic-remote-mount `whoami` $user $namescheme
+ssh $opts $user@$namescheme "touch ~/foo"
+if [ ! -e ~/foo ]; then
+	echo "Failed to create file remotely!"
+	exit 1
+fi
+rm ~/foo
+
 # Stop and snapshot the instance
 echo "Stopping $namescheme"
 gcloud compute instances stop $namescheme
